type: google.api.Service
config_version: 3
name: calendar.googleapis.com
title: Google Calendar API
apis:
  - name: google.calendar.v3.Calendar
authentication:
  providers:
    - id: google_calendar_auth
      jwks_uri: https://www.googleapis.com/oauth2/v1/certs
      issuer: https://securetoken.google.com
  rules:
    - selector: "*"
      requirements:
        provider_id: google_calendar_auth
backend:
  rules:
    - selector: "*"
      address: grpcs://my-service-98sdf8sd0-uc.a.run.app